name: Build and Publish Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gettext nodejs npm

      - name: Install JS dependencies
        run: npm i --legacy-peer-deps

      - name: Run make dist
        run: make dist

      - name: Move dist directory
        run: mv dist/ boot-analysis/

      - name: Compress dist directory
        run: tar -czvf boot-analysis-plugin.tar.gz boot-analysis/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: boot-analysis-plugin
          path: boot-analysis-plugin.tar.gz
