name: cockpit-lib-update
on:
  schedule:
    - cron: '0 2 * * 4'
  workflow_dispatch:
jobs:
  cockpit-lib-update:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Set up dependencies
        run: |
          sudo apt update
          sudo apt install -y make

      - name: Set up git configuration
        run: |
          git config --global user.name "Cockpit Boot Analysis"
          git config --global user.email "cockpit@example.org"

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run cockpit-lib-update
        run: |
          make bots
          bots/cockpit-lib-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update cockpit libs
          branch: cockpit-lib-update-branch
          title: 'Update cockpit libraries'
          body: 'This PR updates the cockpit libraries.'
          labels: update, cockpit
